-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
--
-- vim.api.nvim_create_autocmd("OptionSet", {
--   pattern = "background",
--   callback = function()
--     print(vim.o.background)
--     if vim.o.background == "dark" then
--       vim.cmd.colorscheme("sonokai")
--       vim.g.sonokai_style = "espersso"
--     else
--       vim.cmd.colorscheme("sonokai")
--       vim.g.sonokai_style = "atlantis"
--     end
--   end,
-- })
